# Generated by Django 5.0 on 2023-12-24 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Номенклатура', 'verbose_name_plural': 'Доступные оборудования'},
        ),
        migrations.AlterModelOptions(
            name='deviceinfield',
            options={'verbose_name': 'Оборудование', 'verbose_name_plural': 'Оборудования в полях'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заявку', 'verbose_name_plural': 'Заявки'},
        ),
    ]
